pool:
  name: myPool
  demands: GOPersonalEnvironment

trigger: none

parameters:
- name: VariableGroupName
  displayName: Variable Group Name
  type: string
  default: "docker_ba_vars"

variables:
  - group: ${{ parameters.VariableGroupName }}

steps:
- bash: |
    location=$(curl -s "http://169.254.169.254:80/metadata/instance?api-version=2021-02-01" -H 'Metadata:true' | jq -r '.compute.location')
    echo "##[warning]Pipeline is running in $location"
  displayName: Display Agent Region

- bash: |
    az login --identity -u $(managed_identity_id)
  displayName: AZ login

- bash: |
    tag=$(az acr repository show-tags -n crinfrainstaller --repository helloworld --orderby time_desc --query [0] -o tsv)
    parms="-g $(resource_group_name) -n $(cg_name) --image $(container_image_name):$tag --ports 443 --assign-identity $(managed_identity_id) --acr-identity $(managed_identity_id) --cpu .5 --memory 1.5" 
    parms+=" --secure-environment-variables AZP_TOKEN=$AZDO_PERSONAL_ACCESS_TOKEN" 
    parms+=" --environment-variables AZP_URL=https://dev.azure.com/$(azdo_org_name) AZP_POOL=$(azdo_pool_name) AZP_AGENT_NAME=docker-ba "
    echo "Command invocation parameters: "
    echo $parms
    az container create $parms
  displayName: Deploy latest build agent
  env:
    AZDO_PERSONAL_ACCESS_TOKEN: $(azdo_pat)