import os

CURTAIN_WALL_MODULES_HOME = os.environ.get('CURTAIN_WALL_MODULES_HOME')
CURTAIN_WALL_ENVIRONMENT = os.environ.get('CURTAIN_WALL_ENVIRONMENT')
CURTAIN_WALL_BACKEND_KEY = os.environ.get('CURTAIN_WALL_BACKEND_KEY')