#!/usr/bin/env bash

[ -z "$1" ] && echo "tfvars file name required" && exit 1

echo "Setting up local  terraform environment override"
cat > dev_override.tf <<- EOM
terraform {
  backend "local" {
  }
}
EOM

echo "Init terraform locally"
terraform init

echo "Apply terraform locally"
terraform apply -var-file=$1  -var "install_remote=true"

ARM_STATE_CONTAINER_NAME=`terraform output state_container_name | tr -d '"'`
ARM_STATE_RG_NAME=`terraform output state_rg_name | tr -d '"'`
ARM_STATE_STORAGE_NAME=`terraform output state_storage_name | tr -d '"'`
ARM_STATE_STORAGE_KEY=`terraform output state_key | tr -d '"'`

echo "Removing local override"
rm dev_override.tf

terraform init -backend-config="storage_account_name=$ARM_STATE_STORAGE_NAME" -backend-config="container_name=$ARM_STATE_CONTAINER_NAME" -backend-config="key=$ARM_STATE_STORAGE_KEY" -backend-config="resource_group_name=$ARM_STATE_RG_NAME" -migrate-state

echo "Done"

