#
# Module manifest for module 'ASDKHelper'
#
# Generated by: staskew
#
# Generated on: 22/07/2022
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'ASDKHelper.psm1'

# Version number of this module.
ModuleVersion = '0.1.0'

# ID used to uniquely identify this module
GUID = 'fc635b64-b0c4-4fc6-8ccf-4f2d652c3622'

# Author of this module
Author = 'staskew'

# Company or vendor of this module
CompanyName = 'Microsoft'

# Copyright statement for this module
Copyright = '© Microsoft. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Helper functions to configure an Azure VM for running the Azure Stack Developer Kit (ASDK)'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
	"Initialize-HostOS"
	"Install-Tools"
	"Get-KeyVaultSecret"
	"Get-StackCredentials"
	"Get-NtpServer"
	"Install-ASDK"
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{
	PSData = @{}
}

}
