apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: {{ include "azdo-build-agent.fullname" . }}-job
  namespace: {{ include "azdo-build-agent.fullname" . }}
  labels:
    {{- include "azdo-build-agent.labels" . | nindent 4 }}
spec:
  jobTargetRef:
    ttlSecondsAfterFinished: {{ .Values.scaledJob.ttlSecondsAfterFinished }}
    template:
      spec:
        nodeSelector:
          agentpool: {{.Values.agentPoolNodeSelector }}
        containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: AZP_URL
            valueFrom:
              secretKeyRef:
                name: {{ include "azdo-build-agent.fullname" . }}-secret-azdo
                key: AZP_URL
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ include "azdo-build-agent.fullname" . }}-secret-azdo
                key: AZP_TOKEN
          - name: AZP_POOL
            valueFrom:
              secretKeyRef:
                name: {{ include "azdo-build-agent.fullname" . }}-secret-azdo
                key: AZP_POOL
          - name: AZP_RUN_ONCE
            value: "TRUE"
          - name: DOCKER_IMAGE_NAME
            value: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-volume
        volumes:
        - name: docker-volume
          hostPath:
            path: /var/run/docker.sock
  pollingInterval: {{ .Values.scaledJob.pollingInterval }}
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  maxReplicaCount: {{ .Values.scaledJob.maxReplicaCount }}   
  scalingStrategy:
    strategy: "default"               
  triggers:
  - type: azure-pipelines
    metadata:
      poolName: "{{ .Values.azdo.pool.name | urlquery }}"
      organizationURLFromEnv: "AZP_URL"
      personalAccessTokenFromEnv: "AZP_TOKEN"