apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azdo-build-agent.fullname" . }}-secret-azdo
  namespace: {{ include "azdo-build-agent.fullname" . }}
type: Opaque
data:
  AZP_URL: {{ .Values.azdo.url | b64enc }}
  AZP_TOKEN: {{ .Values.azdo.agentManagementToken | b64enc }}
  AZP_POOL: {{ .Values.azdo.pool.name | b64enc }}