$env:ARM_RESOURCE_LOCATION      = "uksouth"
$env:VHD_OR_IMAGE               = "vhd"
$env:VHD_CAPTURE_CONTAINER_NAME = "curtain-wall"
$env:VHD_CAPTURE_NAME_PREFIX    = "basic-build-agent"
$env:VHD_RESOURCE_GROUP_NAME    = "rg-misc"
$env:VHD_STORAGE_ACCOUNT        = "golivemisc"
$env:ARM_MANAGED_IMAGE_RG_NAME  = "rg-myManagedImages"
$env:ARM_MANAGED_IMAGE_NAME     = "basic-build-agent"

$env:ARM_USE_INTERACTIVE_AUTH  = $false
$env:ARM_TENANT_ID             = "16b3c013-d300-468d-ac64-7eda0820b6d3"
$env:ARM_SUBSCRIPTION_ID       = "f7f45675-6cc1-42c8-9f31-6bd199f7c706"
$env:ARM_CLIENT_ID             = "93d39a2d-cad5-4fa4-8406-9a0816129f44"
$env:ARM_CLIENT_SECRET         = "JTo8Q~xTwfJbBfCp4dG3ja_3ESEtthmjqPrdfbfg"
$env:INSTALL_PASSWORD          = "R3all7L0ngP@ssw0rd!"
