{{- if .Values.ingress.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "nexus.fullname" . }}-nexus-letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.clusterIssuer.email }}
    privateKeySecretRef:
      name: {{ include "nexus.fullname" . }}-nexus-letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class: {{ .Values.ingress.nexus.ingressClassName }}
{{- end }}