apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nexus.fullname" . }}-pvc
  namespace: {{ include "nexus.fullname" . }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: {{ include "nexus.fullname" . }}-pv
  resources:
    requests:
      storage: 250Gi