# Documentation for ACL policy: https://aka.ms/gim/docs/policy/acl

name: Access control list
description: List of teams and their permission levels
resource: repository
where:
configuration:
  manageAccess:
  - team: innersourceise
    role: Read
  - member: golive
    role: Maintain
  - team: CSE-GOV-lever
    role: Maintain
