trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - group: mycurtainwall__test-remote__core
  - group: mycurtainwall__test-remote__hub

steps:
- script: |
    export TF_VAR_azdo_org_name = "$(azdo_org_name)"
    export TF_VAR_azdo_pat = "$(azdo_pat)"

    echo "TF_VAR_azdo_org_name = " $TF_VAR_azdo_org_name
    echo "TF_VAR_azdo_pat = " $TF_VAR_azdo_pat
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
