trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - group: mycurtainwall__test-remote__core
  - group: mycurtainwall__test-remote__hub

steps:
- script: |
    echo "azdo_org_name = " $(azdo_org_name)
  displayName: 'examine var'
    
- script: |
    export TF_VAR_azdo_org_name=$(azdo_org_name)
    echo "TF_VAR_azdo_org_name =" $TF_VAR_azdo_org_name
  displayName: 'examine env vars'
