trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - template: variables.yaml

steps:
- script: |
    echo azdo org name is $AZDO_ORG_NAME
    . remote/setenv.sh
    echo tf var azdo org name is $TF_VAR_azdo_org_name
  displayName: 'set var'
    
