trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - group: mycurtainwall__test-remote__core
  - group: mycurtainwall__test-remote__hub

steps:
- script: |
    echo azdo org name is $AZDO_ORG_NAME
    . remote/setenv.sh
    echo tf var azdo org name is $TF_VAR_azdo_org_name
  displayName: 'set var'
    
- script: |
    echo azdo org name is $AZDO_ORG_NAME
    envsubst < remote/tfvar.tmpl > remote/my.tfvars
    cat remote/my.tfvars
  displayName: 'tfvars'
  env:
    AZDO_PAT: $(azdo_pat)
